// Built-in quote library — discipline, stoicism, keeping going.
// Mixed together with your own whys on the home screen.
const QUOTES = [
  { t: "We suffer more often in imagination than in reality.", s: "Seneca" },
  { t: "You have power over your mind — not outside events. Realize this, and you will find strength.", s: "Marcus Aurelius" },
  { t: "Waste no more time arguing about what a good man should be. Be one.", s: "Marcus Aurelius" },
  { t: "The impediment to action advances action. What stands in the way becomes the way.", s: "Marcus Aurelius" },
  { t: "No man is free who is not master of himself.", s: "Epictetus" },
  { t: "First say to yourself what you would be; and then do what you have to do.", s: "Epictetus" },
  { t: "It's not that we have a short time to live, but that we waste a lot of it.", s: "Seneca" },
  { t: "Discipline is choosing between what you want now and what you want most.", s: "Abraham Lincoln (attributed)" },
  { t: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", s: "Will Durant, on Aristotle" },
  { t: "He who has a why to live can bear almost any how.", s: "Friedrich Nietzsche" },
  { t: "Fall seven times, stand up eight.", s: "Japanese proverb" },
  { t: "The best time to plant a tree was twenty years ago. The second best time is now.", s: "Proverb" },
  { t: "It does not matter how slowly you go as long as you do not stop.", s: "Confucius" },
  { t: "A journey of a thousand miles begins with a single step.", s: "Lao Tzu" },
  { t: "When you arise in the morning, think of what a precious privilege it is to be alive — to breathe, to think, to enjoy, to love.", s: "Marcus Aurelius" },
  { t: "Hard choices, easy life. Easy choices, hard life.", s: "Jerzy Gregorek" },
  { t: "You don't rise to the level of your goals. You fall to the level of your systems.", s: "James Clear" },
  { t: "Every action you take is a vote for the type of person you wish to become.", s: "James Clear" },
  { t: "Motivation gets you going, but discipline keeps you growing.", s: "John C. Maxwell" },
  { t: "Suffer the pain of discipline or suffer the pain of regret.", s: "Jim Rohn" },
  { t: "Don't wish it were easier. Wish you were better.", s: "Jim Rohn" },
  { t: "How you do anything is how you do everything.", s: "Zen saying" },
  { t: "The man who moves a mountain begins by carrying away small stones.", s: "Confucius" },
  { t: "Do something today that your future self will thank you for.", s: "Sean Patrick Flanery" },
  { t: "You will never always be motivated. You have to learn to be disciplined.", s: "Unknown" },
  { t: "A river cuts through rock not because of its power, but because of its persistence.", s: "James N. Watkins" },
  { t: "Rock bottom became the solid foundation on which I rebuilt my life.", s: "J.K. Rowling" },
  { t: "The comeback is always stronger than the setback.", s: "Unknown" },
  { t: "You don't have to see the whole staircase, just take the first step.", s: "Martin Luther King Jr." },
  { t: "Courage doesn't always roar. Sometimes it's the quiet voice at the end of the day saying, 'I will try again tomorrow.'", s: "Mary Anne Radmacher" },
  { t: "If you're going through hell, keep going.", s: "Winston Churchill (attributed)" },
  { t: "It always seems impossible until it's done.", s: "Nelson Mandela" },
  { t: "The greatest glory in living lies not in never falling, but in rising every time we fall.", s: "Nelson Mandela" },
  { t: "Between stimulus and response there is a space. In that space is our power to choose our response.", s: "Viktor Frankl (attributed)" },
  { t: "When we are no longer able to change a situation, we are challenged to change ourselves.", s: "Viktor Frankl" },
  { t: "Those who have a 'why' to live, can bear with almost any 'how'.", s: "Viktor Frankl" },
  { t: "One day, in retrospect, the years of struggle will strike you as the most beautiful.", s: "Sigmund Freud" },
  { t: "Act as if what you do makes a difference. It does.", s: "William James" },
  { t: "Begin at once to live, and count each separate day as a separate life.", s: "Seneca" },
  { t: "Someday you will look back and know exactly why it had to happen.", s: "Unknown" },
  { t: "You are allowed to be both a masterpiece and a work in progress at the same time.", s: "Sophia Bush" },
  { t: "Small steps every day. You don't have to be great to start, but you have to start to be great.", s: "Zig Ziglar" },
  { t: "The pain you feel today will be the strength you feel tomorrow.", s: "Unknown" },
  { t: "Your future needs you. Your past doesn't.", s: "Unknown" },
  { t: "Nothing will work unless you do.", s: "Maya Angelou" },
  { t: "You may not control all the events that happen to you, but you can decide not to be reduced by them.", s: "Maya Angelou" },
  { t: "What you do every day matters more than what you do once in a while.", s: "Gretchen Rubin" },
  { t: "Amateurs sit and wait for inspiration; the rest of us just get up and go to work.", s: "Stephen King" },
  { t: "The secret of getting ahead is getting started.", s: "Mark Twain (attributed)" },
  { t: "Twenty years from now you will be more disappointed by the things you didn't do than by the ones you did.", s: "H. Jackson Brown Jr." },
  { t: "Don't count the days. Make the days count.", s: "Muhammad Ali" },
  { t: "I hated every minute of training, but I said: don't quit. Suffer now and live the rest of your life as a champion.", s: "Muhammad Ali" },
  { t: "Discipline equals freedom.", s: "Jocko Willink" },
  { t: "Don't expect to be motivated every day. You won't be. Rely on discipline, not motivation.", s: "Jocko Willink" },
  { t: "Get after it.", s: "Jocko Willink" },
  { t: "Someone once told me not to bite off more than I could chew. I said I'd rather choke on greatness than nibble on mediocrity.", s: "Unknown" },
  { t: "Whether you think you can or you think you can't — you're right.", s: "Henry Ford" },
  { t: "Energy and persistence conquer all things.", s: "Benjamin Franklin" },
  { t: "Well begun is half done.", s: "Aristotle (attributed)" },
  { t: "This too shall pass.", s: "Persian adage" },
  { t: "No mud, no lotus.", s: "Thich Nhat Hanh" },
  { t: "Just keep swimming.", s: "Dory" }
];
